import 'package:pizzathon/domain/entities/pizza_image_metadata.dart';
import 'package:pizzathon/domain/entities/validation_result.dart';

/// Base sealed class for all pizza validation rules.
/// Each subclass encapsulates a single validation rule.
/// The [validate] method returns a [ValidationResult].
sealed class PizzaValidationRule {
  const PizzaValidationRule();

  /// Returns ValidationSuccess if the image passes, or ValidationRejected/ValidationUnsure.
  ValidationResult validate(PizzaImageMetadata metadata);
}

/// Requires the image to have EXIF data.
/// Rejects screenshots or downloaded images that have no metadata.
class RequireExifDataRule extends PizzaValidationRule {
  const RequireExifDataRule();

  @override
  ValidationResult validate(PizzaImageMetadata metadata) {
    if (!metadata.hasExif) {
      return const ValidationUnsure(
        'La imagen no contiene metadata EXIF. Es posible que sea un screenshot o una imagen descargada.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images whose EXIF software field indicates a screenshot tool.
class DisallowScreenshotsRule extends PizzaValidationRule {
  const DisallowScreenshotsRule();

  @override
  ValidationResult validate(PizzaImageMetadata metadata) {
    if (metadata is DetailedImageMetadata && metadata.isLikelyScreenshot) {
      return const ValidationRejected(
        'La imagen parece ser una captura de pantalla según el software de creación.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images older than [maxAge].
class MaxAgeRule extends PizzaValidationRule {
  final Duration maxAge;

  const MaxAgeRule({this.maxAge = const Duration(days: 10)});

  @override
  ValidationResult validate(PizzaImageMetadata metadata) {
    if (metadata is! DetailedImageMetadata || metadata.creationDate == null) {
      return const ValidationUnsure('No se pudo determinar la fecha de creación de la imagen.');
    }
    final age = DateTime.now().difference(metadata.creationDate!);
    if (age > maxAge) {
      return ValidationRejected(
        'La foto es demasiado antigua. Debe haber sido tomada en los últimos ${maxAge.inDays} días.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Requires the image to have a known camera make and model in its EXIF data.
class RequireCameraMetadataRule extends PizzaValidationRule {
  const RequireCameraMetadataRule();

  @override
  ValidationResult validate(PizzaImageMetadata metadata) {
    if (metadata is! DetailedImageMetadata || (metadata.make == null && metadata.model == null)) {
      return const ValidationUnsure(
        'No se detectó información de cámara. La imagen podría no haber sido tomada con un dispositivo móvil.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images generated by Artificial Intelligence models.
class DisallowAIGeneratedRule extends PizzaValidationRule {
  const DisallowAIGeneratedRule();

  @override
  ValidationResult validate(PizzaImageMetadata metadata) {
    if (metadata.isC2paAiGenerated) {
      return const ValidationRejected(
        'La imagen ha sido identificada como generada por IA mediante Credenciales de Contenido (C2PA).',
      );
    }

    if (metadata is DetailedImageMetadata && metadata.isLikelyAIGenerated) {
      return const ValidationRejected(
        'La imagen parece haber sido generada por Inteligencia Artificial según su metadata.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images processsed by AI models via Content Credentials (C2PA).
/// If not AI, but contains C2PA, it might be an edited image.
class DisallowC2paAIGeneratedRule extends PizzaValidationRule {
  const DisallowC2paAIGeneratedRule();

  @override
  ValidationResult validate(PizzaImageMetadata metadata) {
    if (metadata.isC2paAiGenerated) {
      return const ValidationRejected(
        'La imagen contiene credenciales de contenido (C2PA) indicando que fue generada por IA.',
      );
    }

    // If it has C2PA but is not AI, maybe we should be unsure?
    // For now, if it's not AI, we allow it to continue to other rules.
    return const ValidationSuccess();
  }
}
