import 'dart:typed_data';

sealed class PizzaImageMetadata {
  final Map<String, dynamic>? c2paData;
  final Uint8List? bytes;

  const PizzaImageMetadata({this.c2paData, this.bytes});

  bool get hasExif => false;

  /// Whether the C2PA metadata indicates this image was generated by AI.
  bool get isC2paAiGenerated {
    if (c2paData == null) return false;

    try {
      final manifests = c2paData!['manifests'] as Map<String, dynamic>?;
      if (manifests == null) return false;

      // Check all manifests in the tree, not just the active one.
      // High-end AI tools like ChatGPT/OpenAI often place the AI indicator
      // in an ingredient manifest rather than the top-level active manifest.
      for (final manifestEntry in manifests.values) {
        if (manifestEntry is! Map<String, dynamic>) continue;

        final assertions = manifestEntry['assertions'] as List<dynamic>?;
        if (assertions == null) continue;

        for (final assertion in assertions) {
          if (assertion is Map<String, dynamic> &&
              assertion['label'] == 'c2pa.actions.v2') {
            final data = assertion['data'] as Map<String, dynamic>?;
            final actions = data?['actions'] as List<dynamic>?;
            if (actions != null) {
              for (final action in actions) {
                if (action is Map<String, dynamic>) {
                  final digitalSourceType =
                      action['digitalSourceType'] as String?;
                  // trainedAlgorithmicMedia is the IPTC standard for AI-generated content
                  if (digitalSourceType != null &&
                      digitalSourceType.contains('trainedAlgorithmicMedia')) {
                    return true;
                  }
                  final description = action['description'] as String?;
                  if (description != null) {
                    final descLower = description.toLowerCase();
                    if (descLower.contains('generative ai') ||
                        descLower.contains('ai generated') ||
                        descLower.contains('synthid')) {
                      return true;
                    }
                  }
                }
              }
            }
          }
        }
      }
    } catch (e) {
      return false;
    }
    return false;
  }
}

class DetailedImageMetadata extends PizzaImageMetadata {
  final DateTime? creationDate;
  final String? make;
  final String? model;
  final String? software;
  final bool _hasExif;

  DetailedImageMetadata({
    this.creationDate,
    this.make,
    this.model,
    this.software,
    required bool hasExif,
    super.c2paData,
    super.bytes,
  }) : _hasExif = hasExif;

  @override
  bool get hasExif => _hasExif;

  bool get isLikelyScreenshot {
    if (software != null && software!.toLowerCase().contains('screenshot')) {
      return true;
    }
    return false;
  }

  bool get isLikelyAIGenerated {
    if (isC2paAiGenerated) return true;

    if (software == null) return false;
    final s = software!.toLowerCase();
    return s.contains('midjourney') ||
        s.contains('dall-e') ||
        s.contains('openai') ||
        s.contains('stable diffusion') ||
        s.contains('canva') ||
        s.contains('adobe firefly');
  }
}

class EmptyImageMetadata extends PizzaImageMetadata {
  const EmptyImageMetadata({super.c2paData, super.bytes});
}
