sealed class PizzaImageMetadata {
  final Map<String, dynamic>? c2paData;
  const PizzaImageMetadata({this.c2paData});

  bool get hasExif => false;

  /// Whether the C2PA metadata indicates this image was generated by AI.
  bool get isC2paAiGenerated {
    if (c2paData == null) return false;

    try {
      final activeManifestLabel = c2paData!['active_manifest'] as String?;
      final manifests = c2paData!['manifests'] as Map<String, dynamic>?;

      if (activeManifestLabel == null || manifests == null) return false;

      final activeManifest = manifests[activeManifestLabel] as Map<String, dynamic>?;
      if (activeManifest == null) return false;

      final assertions = activeManifest['assertions'] as List<dynamic>?;
      if (assertions == null) return false;

      for (final assertion in assertions) {
        if (assertion is Map<String, dynamic> && assertion['label'] == 'c2pa.actions.v2') {
          final data = assertion['data'] as Map<String, dynamic>?;
          final actions = data?['actions'] as List<dynamic>?;
          if (actions != null) {
            for (final action in actions) {
              if (action is Map<String, dynamic>) {
                final digitalSourceType = action['digitalSourceType'] as String?;
                // trainedAlgorithmicMedia is the IPTC standard for AI-generated content
                if (digitalSourceType != null &&
                    digitalSourceType.contains('trainedAlgorithmicMedia')) {
                  return true;
                }
                final description = action['description'] as String?;
                if (description != null) {
                  final descLower = description.toLowerCase();
                  if (descLower.contains('generative ai') ||
                      descLower.contains('ai generated') ||
                      descLower.contains('synthid')) {
                    return true;
                  }
                }
              }
            }
          }
        }
      }
    } catch (e) {
      return false;
    }
    return false;
  }
}

class DetailedImageMetadata extends PizzaImageMetadata {
  final DateTime? creationDate;
  final String? make;
  final String? model;
  final String? software;
  final bool _hasExif;

  DetailedImageMetadata({
    this.creationDate,
    this.make,
    this.model,
    this.software,
    required bool hasExif,
    super.c2paData,
  }) : _hasExif = hasExif;

  @override
  bool get hasExif => _hasExif;

  bool get isLikelyScreenshot {
    if (software != null && software!.toLowerCase().contains('screenshot')) {
      return true;
    }
    return false;
  }

  bool get isLikelyAIGenerated {
    if (isC2paAiGenerated) return true;

    if (software == null) return false;
    final s = software!.toLowerCase();
    return s.contains('midjourney') ||
        s.contains('dall-e') ||
        s.contains('openai') ||
        s.contains('stable diffusion') ||
        s.contains('canva') ||
        s.contains('adobe firefly');
  }
}

class EmptyImageMetadata extends PizzaImageMetadata {
  const EmptyImageMetadata({super.c2paData});
}
