import 'package:pizzathon/domain/entities/pizza_image_metadata.dart';
import 'package:pizzathon/domain/entities/validation_result.dart';

/// Base sealed class for all pizza validation rules.
/// Each subclass encapsulates a single validation rule.
/// The [validate] method returns a [ValidationResult].
sealed class PizzaValidationRule {
  const PizzaValidationRule();

  /// A descriptive name for the rule.
  String get name;

  /// Returns ValidationSuccess if the image passes, or ValidationRejected/ValidationDisqualified.
  Future<ValidationResult> validate(PizzaImageMetadata metadata);
}

/// Requires the image to have EXIF data.
/// Rejects screenshots or downloaded images that have no metadata.
class RequireExifDataRule extends PizzaValidationRule {
  const RequireExifDataRule();

  @override
  String get name => 'Metadatos EXIF';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (!metadata.hasExif) {
      return ValidationRejected(
        'La imagen no es una foto tomada con tu telefono\n INCUMPLE LAS NORMAS',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images whose EXIF software field indicates a screenshot tool.
class DisallowScreenshotsRule extends PizzaValidationRule {
  const DisallowScreenshotsRule();

  @override
  String get name => 'Captura de pantalla';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata is DetailedImageMetadata && metadata.isLikelyScreenshot) {
      return const ValidationRejected(
        'La imagen escogida podria ser una captura de pantalla, no es una foto \n INCUMPLE LAS NORMAS',
      );
    }
    return const ValidationSuccess();
  }
}


/// Requires the image to have a known camera make and model in its EXIF data.
class RequireCameraMetadataRule extends PizzaValidationRule {
  const RequireCameraMetadataRule();

  @override
  String get name => 'Información de cámara';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata is! DetailedImageMetadata ||
        (metadata.make == null && metadata.model == null)) {
      return ValidationRejected(
        'No se detectó información de cámara. La imagen podría no haber sido tomada con un dispositivo móvil\n INCUMPLE LAS NORMAS',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images generated by Artificial Intelligence models.
class DisallowAIGeneratedRule extends PizzaValidationRule {
  const DisallowAIGeneratedRule();

  @override
  String get name => 'Generada por IA';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata.isC2paAiGenerated) {
      return const ValidationDisqualified(
        'La imagen ha sido identificada como generada por IA mediante Credenciales de Contenido (C2PA).',
      );
    }

    if (metadata is DetailedImageMetadata && metadata.isLikelyAIGenerated) {
      return const ValidationDisqualified(
        'La imagen parece haber sido generada por Inteligencia Artificial según su metadata.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images processsed by AI models via Content Credentials (C2PA).
/// If not AI, but contains C2PA, it might be an edited image.
class DisallowC2paAIGeneratedRule extends PizzaValidationRule {
  const DisallowC2paAIGeneratedRule();

  @override
  String get name => 'Credenciales de Contenido (C2PA)';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata.isC2paAiGenerated) {
      return const ValidationDisqualified(
        'La imagen contiene credenciales de contenido (C2PA) indicando que fue generada por IA.',
      );
    }

    // If it has C2PA but is not AI, maybe we should be unsure?
    // For now, if it's not AI, we allow it to continue to other rules.
    return const ValidationSuccess();
  }
}

class ContestDateRangeRule extends PizzaValidationRule {
  final DateTime startDate;
  final DateTime endDate;

  const ContestDateRangeRule({required this.startDate, required this.endDate});

  @override
  String get name => 'Fechas del concurso';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata is! DetailedImageMetadata || metadata.creationDate == null) {
      return const ValidationRejected(
        'No se pudo determinar la fecha exacta de creación de la imagen.',
      );
    }

    final creationDate = metadata.creationDate!;

    if (creationDate.isBefore(startDate) || creationDate.isAfter(endDate)) {
      return ValidationRejected(
        'La foto se tomó fuera de las fechas del concurso (del ${startDate.day}/${startDate.month} al ${endDate.day}/${endDate.month}).',
      );
    }

    return const ValidationSuccess();
  }
}
