import 'package:pizzathon/domain/entities/pizza_image_metadata.dart';
import 'package:pizzathon/domain/entities/validation_result.dart';
import 'package:pizzathon/data/services/moire/moire_service.dart';
import 'dart:typed_data';

/// Base sealed class for all pizza validation rules.
/// Each subclass encapsulates a single validation rule.
/// The [validate] method returns a [ValidationResult].
sealed class PizzaValidationRule {
  const PizzaValidationRule();

  /// A descriptive name for the rule.
  String get name;

  /// Returns ValidationSuccess if the image passes, or ValidationRejected/ValidationUnsure.
  Future<ValidationResult> validate(PizzaImageMetadata metadata);
}

/// Requires the image to have EXIF data.
/// Rejects screenshots or downloaded images that have no metadata.
class RequireExifDataRule extends PizzaValidationRule {
  const RequireExifDataRule();

  @override
  String get name => 'Metadatos EXIF';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (!metadata.hasExif) {
      return ValidationRejected(
        'La imagen no contiene metadata EXIF. Es posible que sea un screenshot o una imagen descargada.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images whose EXIF software field indicates a screenshot tool.
class DisallowScreenshotsRule extends PizzaValidationRule {
  const DisallowScreenshotsRule();

  @override
  String get name => 'Captura de pantalla';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata is DetailedImageMetadata && metadata.isLikelyScreenshot) {
      return const ValidationRejected(
        'La imagen parece ser una captura de pantalla según el software de creación.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images older than [maxAge].
class MaxAgeRule extends PizzaValidationRule {
  final Duration maxAge;

  const MaxAgeRule({this.maxAge = const Duration(days: 10)});

  @override
  String get name => 'Antigüedad de la foto';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata is! DetailedImageMetadata || metadata.creationDate == null) {
      return ValidationRejected('No se pudo determinar la fecha de creación de la imagen.');
    }
    final age = DateTime.now().difference(metadata.creationDate!);
    if (age > maxAge) {
      return ValidationRejected(
        'La foto es demasiado antigua. Debe haber sido tomada en los últimos ${maxAge.inDays} días.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Requires the image to have a known camera make and model in its EXIF data.
class RequireCameraMetadataRule extends PizzaValidationRule {
  const RequireCameraMetadataRule();

  @override
  String get name => 'Información de cámara';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata is! DetailedImageMetadata || (metadata.make == null && metadata.model == null)) {
      return ValidationRejected(
        'No se detectó información de cámara. La imagen podría no haber sido tomada con un dispositivo móvil.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images generated by Artificial Intelligence models.
class DisallowAIGeneratedRule extends PizzaValidationRule {
  const DisallowAIGeneratedRule();

  @override
  String get name => 'Generada por IA';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata.isC2paAiGenerated) {
      return const ValidationRejected(
        'La imagen ha sido identificada como generada por IA mediante Credenciales de Contenido (C2PA).',
      );
    }

    if (metadata is DetailedImageMetadata && metadata.isLikelyAIGenerated) {
      return const ValidationRejected(
        'La imagen parece haber sido generada por Inteligencia Artificial según su metadata.',
      );
    }
    return const ValidationSuccess();
  }
}

/// Rejects images processsed by AI models via Content Credentials (C2PA).
/// If not AI, but contains C2PA, it might be an edited image.
class DisallowC2paAIGeneratedRule extends PizzaValidationRule {
  const DisallowC2paAIGeneratedRule();

  @override
  String get name => 'Credenciales de Contenido (C2PA)';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    if (metadata.isC2paAiGenerated) {
      return const ValidationRejected(
        'La imagen contiene credenciales de contenido (C2PA) indicando que fue generada por IA.',
      );
    }

    // If it has C2PA but is not AI, maybe we should be unsure?
    // For now, if it's not AI, we allow it to continue to other rules.
    return const ValidationSuccess();
  }
}

/// Rejects images displaying Moire patterns, often indicative of re-photographing a screen.
class DisallowMoireRule extends PizzaValidationRule {
  const DisallowMoireRule();

  @override
  String get name => 'Patrones de Moiré';

  @override
  Future<ValidationResult> validate(PizzaImageMetadata metadata) async {
    final bytes = metadata.bytes;
    if (bytes == null || bytes.isEmpty) {
      // If no bytes, we can't check for Moire, but we don't necessarily reject.
      // Or maybe we should be unsure? For now, success if check not possible.
      return const ValidationSuccess();
    }

    final isMoire = await MoireService().detectMoireFromBytes(Uint8List.fromList(bytes));
    if (isMoire) {
      return const ValidationRejected(
        'Se detectaron patrones de Moiré en la imagen. Esto sugiere que la foto es de una pantalla.',
      );
    }
    return const ValidationSuccess();
  }
}

